import pandas as pd
df = pd.read_csv("students.csv")
print(df)
print(df.head())
print(df.describe())
print(df.info())
print(df["Marks"].mean())
sorted_df = df.sort_values("Marks")
print(sorted_df)
sorted_desc = df.sort_values("Marks", ascending=False)
print(sorted_desc)